### ISSUE TITLE
Setup Project Architecture

### ISSUE THREAD

**Issue by jeremyglebe** [Kings-Tithe/Project_Dungeon#20]
Things to consider:
- a clear file structure is critical to maintaining the project
- generally, naming conventions and comment structures should be uniform
  - these conventions need to be listed under `## Conventions` with examples in the readme of relevant folders
- build scripts are necessary for rapid testing and production
  - we'll need scripts to compile typescript to js, but also to build final desktop applications
  - minimizing the production build is very important
  - ideally, all building tools will be run through easy to remember and simple commands (ex: `yarn build`)
- clear client/server relations need to be established
  - the server synchronizes clients but does not have a "strong control"
    - this makes it easy to cheat but its a small party co-op game so this isn't super concerning
  - game will be run client-first which means the client needs to be driving gameplay but able to reverse actions or correct when the server sends sync data

**Comment by zachkingcade** [comment]
File Structure set up by the following commit(s):
https://github.com/zachkingcade/Project_Dungeon/commit/ecd0943bfb2802fc6e2163569cf86f68893c979d
https://github.com/zachkingcade/Project_Dungeon/commit/1ceff5bf17e2ee545585e7b4a3800b3221c5e3c6
https://github.com/zachkingcade/Project_Dungeon/commit/4789dc57d6db416d541d37e2ba574b968e8f7d03
Note:
Still need to setup a commenting standard

**Comment by jeremyglebe** [comment]
> File Structure set up by the following commit(s):
> [ecd0943](https://github.com/zachkingcade/Project_Dungeon/commit/ecd0943bfb2802fc6e2163569cf86f68893c979d)
> [1ceff5b](https://github.com/zachkingcade/Project_Dungeon/commit/1ceff5bf17e2ee545585e7b4a3800b3221c5e3c6)
> [4789dc5](https://github.com/zachkingcade/Project_Dungeon/commit/4789dc57d6db416d541d37e2ba574b968e8f7d03)
> Note:
> Still need to setup a commenting standard
This is not what is meant by architecture.

**Comment by jeremyglebe** [comment]
completed build scripts and we have a general client/server concept
